<?php

namespace Holyc;

class CodeGenError extends \RuntimeException {}

/**
 * Walking-skeleton x86-64 NASM code generator (System V AMD64, Linux).
 *
 * Strategy: simple stack-based codegen. Every expression evaluates into RAX.
 * For binary ops, the right operand is evaluated first, pushed, then the left
 * operand is evaluated, the right is popped into RCX, and the op is performed.
 * Locals live on the stack at fixed offsets from RBP; a per-function symbol
 * table maps name -> RBP offset.
 *
 * The runtime is a tiny `_start` stub that calls `main` and uses its return
 * value as the process exit code (so `return 42;` exits 42).
 *
 * Supported subset:
 *   - Function declarations with up to 6 integer/pointer params (RDI..R9)
 *   - Local I64 variable declarations with optional initializer
 *   - Integer literal expressions
 *   - Arithmetic: + - * /
 *   - Comparison: == != < <= > >=  (produce 0/1 in RAX)
 *   - Logical: && || (short-circuiting)
 *   - Unary: -, !
 *   - Variable read/write
 *   - Assignment to a local
 *   - If/else, while, for, break
 *   - Function calls (caller saves nothing; callee saves rbp only)
 *   - Return
 */
class CodeGen {
    /** @var string[] emitted lines for the .text section */
    private array $text = [];

    /** @var array<string,int> name -> rbp offset (negative) for current function */
    private array $locals = [];
    /** @var int next free slot offset (negative, multiple of 8) */
    private int $nextLocalOffset = 0;

    /** @var string[] stack of break-target labels for the innermost loop */
    private array $breakStack = [];

    /** @var string|null label to jump to from `return` in current function */
    private ?string $returnLabel = null;

    private int $labelCounter = 0;

    /** Param-passing registers in System V AMD64 order. */
    private const ARG_REGS = ['rdi', 'rsi', 'rdx', 'rcx', 'r8', 'r9'];

    public function compile(Program $program): string {
        $this->text = [];
        $this->emit("; generated by holyc-php");
        $this->emit("BITS 64");
        $this->emit("section .text");
        $this->emit("global _start");
        $this->emit("");
        $this->emit("_start:");
        $this->emit("    call main");
        $this->emit("    mov rdi, rax");
        $this->emit("    mov rax, 60");          // sys_exit
        $this->emit("    syscall");
        $this->emit("");

        foreach ($program->decls->items as $decl) {
            if ($decl instanceof FuncDecl) {
                if ($decl->body !== null) {
                    $this->compileFunc($decl);
                }
            }
            // ClassDecl, top-level VarDecl, top-level stmts: not yet supported.
        }

        return implode("\n", $this->text) . "\n";
    }

    /* ------------------------------------------------------------------ *
     * Functions
     * ------------------------------------------------------------------ */

    private function compileFunc(FuncDecl $f): void {
        $this->locals = [];
        $this->nextLocalOffset = 0;
        $this->returnLabel = $this->newLabel(".L" . $f->name . "_ret");

        // Pre-pass: assign stack slots for every local variable in this
        // function (params + body decls).
        foreach ($f->params->items as $p) {
            if ($p->name !== null) $this->allocLocal($p->name);
        }
        $this->collectLocals($f->body);

        // 16-byte align the frame so calls into libc behave.
        $frameSize = $this->align16($this->nextLocalOffset === 0 ? 0 : -$this->nextLocalOffset);

        $this->emit($f->name . ":");
        $this->emit("    push rbp");
        $this->emit("    mov rbp, rsp");
        if ($frameSize > 0) {
            $this->emit("    sub rsp, $frameSize");
        }

        // Spill incoming params into their slots.
        foreach ($f->params->items as $i => $p) {
            if ($i >= count(self::ARG_REGS)) {
                throw new CodeGenError("more than 6 params not supported yet");
            }
            if ($p->name !== null) {
                $off = $this->locals[$p->name];
                $reg = self::ARG_REGS[$i];
                $this->emit("    mov [rbp{$off}], $reg");
            }
        }

        $this->compileStmt($f->body);

        // Default return value if control fell off the end.
        $this->emit($this->returnLabel . ":");
        $this->emit("    mov rsp, rbp");
        $this->emit("    pop rbp");
        $this->emit("    ret");
        $this->emit("");

        $this->returnLabel = null;
    }

    /**
     * Walk a statement subtree and register stack slots for every VarDecl.
     */
    private function collectLocals(AstNode $node): void {
        if ($node instanceof VarDecl) {
            $this->allocLocal($node->name);
            return;
        }
        if ($node instanceof Block) {
            foreach ($node->stmts->items as $s) $this->collectLocals($s);
            return;
        }
        if ($node instanceof IfStmt) {
            $this->collectLocals($node->then);
            if ($node->else) $this->collectLocals($node->else);
            return;
        }
        if ($node instanceof WhileStmt) {
            $this->collectLocals($node->body);
            return;
        }
        if ($node instanceof ForStmt) {
            if ($node->init instanceof VarDecl) $this->allocLocal($node->init->name);
            $this->collectLocals($node->body);
            return;
        }
        // Other nodes don't introduce locals.
    }

    private function allocLocal(string $name): int {
        if (!isset($this->locals[$name])) {
            $this->nextLocalOffset -= 8;
            $this->locals[$name] = $this->nextLocalOffset;
        }
        return $this->locals[$name];
    }

    /* ------------------------------------------------------------------ *
     * Statements
     * ------------------------------------------------------------------ */

    private function compileStmt(AstNode $s): void {
        if ($s instanceof Block) {
            foreach ($s->stmts->items as $stmt) $this->compileStmt($stmt);
            return;
        }
        if ($s instanceof VarDecl) {
            if ($s->init !== null) {
                $this->compileExpr($s->init);
                $off = $this->locals[$s->name];
                $this->emit("    mov [rbp{$off}], rax");
            }
            return;
        }
        if ($s instanceof ExprStmt) {
            // ReturnStmt is wrapped in ExprStmt by the parser.
            if ($s->expr instanceof ReturnStmt) {
                if ($s->expr->value !== null) {
                    $this->compileExpr($s->expr->value);
                } else {
                    $this->emit("    xor rax, rax");
                }
                $this->emit("    jmp " . $this->returnLabel);
                return;
            }
            $this->compileExpr($s->expr);
            return;
        }
        if ($s instanceof IfStmt) {
            $this->compileIf($s);
            return;
        }
        if ($s instanceof WhileStmt) {
            $this->compileWhile($s);
            return;
        }
        if ($s instanceof ForStmt) {
            $this->compileFor($s);
            return;
        }
        if ($s instanceof BreakStmt) {
            if (empty($this->breakStack)) {
                throw new CodeGenError("`break` outside of loop");
            }
            $this->emit("    jmp " . end($this->breakStack));
            return;
        }
        if ($s instanceof ReturnStmt) {
            // Bare ReturnStmt (not wrapped) — same handling.
            if ($s->value !== null) {
                $this->compileExpr($s->value);
            } else {
                $this->emit("    xor rax, rax");
            }
            $this->emit("    jmp " . $this->returnLabel);
            return;
        }
        throw new CodeGenError("Unsupported statement: " . $s->kind());
    }

    private function compileIf(IfStmt $s): void {
        $elseL = $this->newLabel(".Lelse");
        $endL  = $this->newLabel(".Lendif");
        $this->compileExpr($s->cond);
        $this->emit("    cmp rax, 0");
        $this->emit("    je " . ($s->else ? $elseL : $endL));
        $this->compileStmt($s->then);
        if ($s->else) {
            $this->emit("    jmp $endL");
            $this->emit("$elseL:");
            $this->compileStmt($s->else);
        }
        $this->emit("$endL:");
    }

    private function compileWhile(WhileStmt $s): void {
        $top = $this->newLabel(".Lwhile");
        $end = $this->newLabel(".Lendwhile");
        $this->breakStack[] = $end;
        $this->emit("$top:");
        $this->compileExpr($s->cond);
        $this->emit("    cmp rax, 0");
        $this->emit("    je $end");
        $this->compileStmt($s->body);
        $this->emit("    jmp $top");
        $this->emit("$end:");
        array_pop($this->breakStack);
    }

    private function compileFor(ForStmt $s): void {
        if ($s->init) {
            if ($s->init instanceof VarDecl) {
                $this->compileStmt($s->init);
            } else {
                $this->compileExpr($s->init);
            }
        }
        $top = $this->newLabel(".Lfor");
        $end = $this->newLabel(".Lendfor");
        $this->breakStack[] = $end;
        $this->emit("$top:");
        if ($s->cond) {
            $this->compileExpr($s->cond);
            $this->emit("    cmp rax, 0");
            $this->emit("    je $end");
        }
        $this->compileStmt($s->body);
        if ($s->step) $this->compileExpr($s->step);
        $this->emit("    jmp $top");
        $this->emit("$end:");
        array_pop($this->breakStack);
    }

    /* ------------------------------------------------------------------ *
     * Expressions — result lands in RAX
     * ------------------------------------------------------------------ */

    private function compileExpr(AstNode $e): void {
        if ($e instanceof IntLit) {
            $this->emit("    mov rax, {$e->value}");
            return;
        }
        if ($e instanceof BoolLit) {
            $this->emit("    mov rax, " . ($e->value ? '1' : '0'));
            return;
        }
        if ($e instanceof NullLit) {
            $this->emit("    xor rax, rax");
            return;
        }
        if ($e instanceof IdentExpr) {
            $off = $this->locals[$e->name] ?? null;
            if ($off === null) {
                throw new CodeGenError("Unknown identifier: {$e->name}");
            }
            $this->emit("    mov rax, [rbp{$off}]");
            return;
        }
        if ($e instanceof UnaryExpr) {
            $this->compileUnary($e);
            return;
        }
        if ($e instanceof BinaryExpr) {
            $this->compileBinary($e);
            return;
        }
        if ($e instanceof AssignExpr) {
            $this->compileAssign($e);
            return;
        }
        if ($e instanceof CallExpr) {
            $this->compileCall($e);
            return;
        }
        throw new CodeGenError("Unsupported expression: " . $e->kind());
    }

    private function compileUnary(UnaryExpr $e): void {
        if (!$e->prefix) {
            // Postfix ++ / -- — return the old value, then mutate.
            if (!($e->operand instanceof IdentExpr)) {
                throw new CodeGenError("postfix ++/-- only supported on locals");
            }
            $off = $this->locals[$e->operand->name];
            $this->emit("    mov rax, [rbp{$off}]");
            $delta = $e->op === Token::Increment ? 1 : -1;
            $this->emit("    " . ($delta > 0 ? "add" : "sub") . " qword [rbp{$off}], 1");
            return;
        }
        if ($e->op === Token::Minus) {
            $this->compileExpr($e->operand);
            $this->emit("    neg rax");
            return;
        }
        if ($e->op === Token::Plus) {
            $this->compileExpr($e->operand);
            return;
        }
        if ($e->op === Token::Not) {
            $this->compileExpr($e->operand);
            $this->emit("    cmp rax, 0");
            $this->emit("    sete al");
            $this->emit("    movzx rax, al");
            return;
        }
        if ($e->op === Token::Increment || $e->op === Token::Decrement) {
            // Prefix ++x / --x on a local
            if (!($e->operand instanceof IdentExpr)) {
                throw new CodeGenError("prefix ++/-- only supported on locals");
            }
            $off = $this->locals[$e->operand->name];
            $delta = $e->op === Token::Increment ? "add" : "sub";
            $this->emit("    $delta qword [rbp{$off}], 1");
            $this->emit("    mov rax, [rbp{$off}]");
            return;
        }
        throw new CodeGenError("Unsupported unary op: " . $e->op->value);
    }

    private function compileBinary(BinaryExpr $e): void {
        // Short-circuit evaluation for && and ||.
        if ($e->op === Token::And) {
            $false = $this->newLabel(".Land_false");
            $end   = $this->newLabel(".Land_end");
            $this->compileExpr($e->left);
            $this->emit("    cmp rax, 0");
            $this->emit("    je $false");
            $this->compileExpr($e->right);
            $this->emit("    cmp rax, 0");
            $this->emit("    je $false");
            $this->emit("    mov rax, 1");
            $this->emit("    jmp $end");
            $this->emit("$false:");
            $this->emit("    xor rax, rax");
            $this->emit("$end:");
            return;
        }
        if ($e->op === Token::Or) {
            $true = $this->newLabel(".Lor_true");
            $end  = $this->newLabel(".Lor_end");
            $this->compileExpr($e->left);
            $this->emit("    cmp rax, 0");
            $this->emit("    jne $true");
            $this->compileExpr($e->right);
            $this->emit("    cmp rax, 0");
            $this->emit("    jne $true");
            $this->emit("    xor rax, rax");
            $this->emit("    jmp $end");
            $this->emit("$true:");
            $this->emit("    mov rax, 1");
            $this->emit("$end:");
            return;
        }

        // Standard pattern: eval RHS first, push, eval LHS, pop RHS into rcx.
        $this->compileExpr($e->right);
        $this->emit("    push rax");
        $this->compileExpr($e->left);
        $this->emit("    pop rcx");

        switch ($e->op) {
            case Token::Plus:     $this->emit("    add rax, rcx"); return;
            case Token::Minus:    $this->emit("    sub rax, rcx"); return;
            case Token::Multiply: $this->emit("    imul rax, rcx"); return;
            case Token::Divide:
                $this->emit("    cqo");           // sign-extend rax into rdx
                $this->emit("    idiv rcx");
                return;
            case Token::Modulo:
                $this->emit("    cqo");
                $this->emit("    idiv rcx");
                $this->emit("    mov rax, rdx");
                return;
            case Token::Eq:       $this->cmpAndSet('sete');  return;
            case Token::Ne:       $this->cmpAndSet('setne'); return;
            case Token::Lt:       $this->cmpAndSet('setl');  return;
            case Token::Lte:      $this->cmpAndSet('setle'); return;
            case Token::Gt:       $this->cmpAndSet('setg');  return;
            case Token::Gte:      $this->cmpAndSet('setge'); return;
            case Token::BitwiseAnd: $this->emit("    and rax, rcx"); return;
            case Token::BitwiseOr:  $this->emit("    or rax, rcx");  return;
            case Token::BitwiseXor: $this->emit("    xor rax, rcx"); return;
            case Token::ShiftL:
                $this->emit("    mov rdx, rcx");  // shift count must be cl
                $this->emit("    mov cl, dl");
                $this->emit("    shl rax, cl");
                return;
            case Token::ShiftR:
                $this->emit("    mov rdx, rcx");
                $this->emit("    mov cl, dl");
                $this->emit("    sar rax, cl");
                return;
        }
        throw new CodeGenError("Unsupported binary op: " . $e->op->value);
    }

    private function cmpAndSet(string $setcc): void {
        $this->emit("    cmp rax, rcx");
        $this->emit("    $setcc al");
        $this->emit("    movzx rax, al");
    }

    private function compileAssign(AssignExpr $e): void {
        if (!($e->target instanceof IdentExpr)) {
            throw new CodeGenError("assignment target must be a local for now");
        }
        $name = $e->target->name;
        $off  = $this->locals[$name] ?? null;
        if ($off === null) {
            throw new CodeGenError("Unknown identifier: $name");
        }

        if ($e->op === Token::Equals) {
            $this->compileExpr($e->value);
            $this->emit("    mov [rbp{$off}], rax");
            return;
        }

        // Compound assignment: load, op, store.
        $this->compileExpr($e->value);
        $this->emit("    mov rcx, rax");
        $this->emit("    mov rax, [rbp{$off}]");
        switch ($e->op) {
            case Token::PlusEquals:     $this->emit("    add rax, rcx"); break;
            case Token::MinusEquals:    $this->emit("    sub rax, rcx"); break;
            case Token::MultiplyEquals: $this->emit("    imul rax, rcx"); break;
            case Token::DivideEquals:
                $this->emit("    cqo"); $this->emit("    idiv rcx"); break;
            case Token::ModuloEquals:
                $this->emit("    cqo"); $this->emit("    idiv rcx");
                $this->emit("    mov rax, rdx"); break;
            case Token::BitOrEquals:  $this->emit("    or rax, rcx");  break;
            case Token::BitAndEquals: $this->emit("    and rax, rcx"); break;
            case Token::BitXorEquals: $this->emit("    xor rax, rcx"); break;
            default:
                throw new CodeGenError("Unsupported compound op: " . $e->op->value);
        }
        $this->emit("    mov [rbp{$off}], rax");
    }

    private function compileCall(CallExpr $e): void {
        if (!($e->callee instanceof IdentExpr)) {
            throw new CodeGenError("only direct calls to named functions supported");
        }
        $args = $e->args->items;
        if (count($args) > count(self::ARG_REGS)) {
            throw new CodeGenError("more than 6 args not supported yet");
        }

        // Evaluate args left-to-right, pushing each to keep temp space safe
        // across nested calls. Then pop into the AMD64 arg registers in order.
        foreach ($args as $a) {
            $this->compileExpr($a);
            $this->emit("    push rax");
        }
        for ($i = count($args) - 1; $i >= 0; $i--) {
            $this->emit("    pop " . self::ARG_REGS[$i]);
        }
        // Stack must be 16-byte aligned at the call instruction. The callee's
        // own `push rbp` realigns once we've come from a 16-aligned _start.
        // Since this codegen never uses stack args, alignment is preserved
        // as long as we don't leave dangling pushes — we always pop into regs.
        $this->emit("    call " . $e->callee->name);
    }

    /* ------------------------------------------------------------------ *
     * Helpers
     * ------------------------------------------------------------------ */

    private function emit(string $line): void {
        $this->text[] = $line;
    }

    private function newLabel(string $base): string {
        return $base . "_" . $this->labelCounter++;
    }

    private function align16(int $n): int {
        return ($n + 15) & ~15;
    }
}
